POST http://localhost:8080/user/register
content-type: application/json
X-Requested-With: XMLHttpRequest

{
    "ufName": "Bhupen",
    "ulName": "Pal",
    "uEmail": "bhupen16pal@gmail.com",
    "upNum": 9587551153,
    "uAddr": "MY ADDRESS",
    "uState": "Delhi",
    "uPinCode": "110053",
    "uInsti": "MAIT",
    "uPass": "Hello@123",
    "ucPass": "Hello@123",
    "uRole": "Student"
}